# version: "3.9"  # ← 删除这行

services:
  minio:
    image: minio/minio:latest      # ← 改这里；若网络不稳可用 quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: Suzuhararainbow
      MINIO_ROOT_PASSWORD: Suzuhararainbow1101
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:5173   # ← 新增，仅开发期
    volumes:
      - ./minio-data:/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: media_site
      POSTGRES_USER: media
      POSTGRES_PASSWORD: strongpass
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    env_file: ./.env.dev
    ports:
      - "8088:8080"
    depends_on:
      - postgres
      - minio

  web:
    working_dir: /app
    image: node:20
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
