services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    env_file:
      - ./mysql.prod.env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/10-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 6

  api:
    build:
      context: ../backend
    restart: unless-stopped
    env_file:
      - ./backend.prod.env
    environment:
      MEDIA_ROOT: /app/data/media
    volumes:
      - ./data/media:/app/data/media
    depends_on:
      mysql:
        condition: service_healthy

  web:
    build:
      context: ../frontend
      args:
        VITE_API_BASE: /api
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
