version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: suzuhara_media
      MYSQL_USER: media_app
      MYSQL_PASSWORD: media_app_pass
      MYSQL_ROOT_PASSWORD: root_dev_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/10-schema.sql:ro

  web:
    image: node:20
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    env_file:
      - ./frontend.env
    environment:
      - BROWSER=none
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    depends_on:
      mysql:
        condition: service_healthy

  api:
    build: ../backend
    restart: unless-stopped
    env_file:
      - ./backend.env
    environment:
      MEDIA_ROOT: /app/data/media
    volumes:
      - ../backend:/app
      - ./data/media:/app/data/media
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
